apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker